apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: microservices
        image: alfiodimauro/adm_solutions:api-gateway
        ports:
        - containerPort: 8080
