apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: microservices
        image: alfiodimauro/adm_solutions:product-service
        ports:
        - containerPort: 8081
