apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: microservices
        image: alfiodimauro/adm_solutions:eureka-server
        ports:
        - containerPort: 8761
